#!/bin/bash
# MC Weekly Digest — generates and posts a fleet summary
# Run Fridays at 17:00 HKT via cron
set -euo pipefail

MC_API="https://resilient-chinchilla-241.convex.site"
MC_KEY="232e4ddf7d69c31e01ad0fa0a61f70c29e4837ed018a153cce1a429842bb7cbc"

# Fetch tasks
TASKS=$(curl -s "$MC_API/api/tasks" \
  -H "Authorization: Bearer $MC_KEY")

# Generate digest via Python
DIGEST=$(python3 -c "
import json, sys
from datetime import datetime, timedelta

tasks = json.loads('''$TASKS''')
now = datetime.now()
week_ago = (now - timedelta(days=7)).isoformat()

# Count by status
total = len(tasks)
done = [t for t in tasks if t.get('status') == 'done']
done_this_week = [t for t in done if t.get('completedAt', 0) > (now - timedelta(days=7)).timestamp() * 1000]
in_progress = [t for t in tasks if t.get('status') == 'in_progress']
blocked = [t for t in tasks if t.get('status') == 'blocked']

# Build report
lines = []
lines.append('📊 **TMNT Weekly Digest** — ' + now.strftime('%B %d, %Y'))
lines.append('')
lines.append(f'**Tasks:** {total} total · {len(done_this_week)} completed this week · {len(in_progress)} in progress · {len(blocked)} blocked')
lines.append('')

if done_this_week:
    lines.append('✅ **Completed:**')
    for t in done_this_week[:10]:
        lines.append(f'  • {t[\"title\"]}')
    lines.append('')

if blocked:
    lines.append('🚫 **Blocked:**')
    for t in blocked[:5]:
        lines.append(f'  • {t[\"title\"]}')
    lines.append('')

lines.append('_Generated by Mission Control_')
print('\\n'.join(lines))
")

echo "$DIGEST"
