#!/bin/bash
# MC Weekly Digest — generates and posts a fleet summary
# Run Fridays at 17:00 HKT via cron
set -euo pipefail

MC_API="https://resilient-chinchilla-241.convex.site"
MC_KEY="232e4ddf7d69c31e01ad0fa0a61f70c29e4837ed018a153cce1a429842bb7cbc"

# Fetch tasks to temp file
TASKS_FILE=$(mktemp)
curl -s "$MC_API/api/tasks" \
  -H "Authorization: Bearer $MC_KEY" > "$TASKS_FILE"

# Generate digest via Python
DIGEST=$(python3 << PYTHON_EOF
import json
from datetime import datetime, timedelta

with open('$TASKS_FILE', 'r') as f:
    tasks = json.load(f)

now = datetime.now()

# Count by status
total = len(tasks)
done = [t for t in tasks if t.get('status') == 'done']
done_this_week = [t for t in done if t.get('completedAt', 0) > (now - timedelta(days=7)).timestamp() * 1000]
in_progress = [t for t in tasks if t.get('status') == 'in_progress']
blocked = [t for t in tasks if t.get('status') == 'blocked']

# Build report
lines = []
lines.append('📊 **TMNT Weekly Digest** — ' + now.strftime('%B %d, %Y'))
lines.append('')
lines.append(f'**Tasks:** {total} total · {len(done_this_week)} completed this week · {len(in_progress)} in progress · {len(blocked)} blocked')
lines.append('')

if done_this_week:
    lines.append('✅ **Completed:**')
    for t in done_this_week[:10]:
        lines.append(f'  • {t["title"]}')
    lines.append('')

if blocked:
    lines.append('🚫 **Blocked:**')
    for t in blocked[:5]:
        lines.append(f'  • {t["title"]}')
    lines.append('')

lines.append('_Generated by Mission Control_')
print('\n'.join(lines))
PYTHON_EOF
)

# Cleanup
rm -f "$TASKS_FILE"

echo "$DIGEST"
